ALTER TABLE stores
ADD COLUMN jibun_address VARCHAR(255) NULL;

ALTER TABLE stores
ADD COLUMN haengjeong_code VARCHAR(10) NOT NULL;

ALTER TABLE stores
ADD COLUMN beopjeong_code VARCHAR(10) NOT NULL;

ALTER TABLE stores
ADD COLUMN longitude DOUBLE NOT NULL;

ALTER TABLE stores
ADD COLUMN latitude DOUBLE NOT NULL;

ALTER TABLE stores
ADD COLUMN zipcode VARCHAR(5) NOT NULL;
