-- 가게
CREATE TABLE stores (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  owner_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  address VARCHAR(100) NOT NULL,
  introduction VARCHAR(255) NOT NULL,
  open_status BOOLEAN NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

-- 메뉴
CREATE TABLE menus (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  store_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  photo_url VARCHAR(500) NOT NULL,
  price DECIMAL(10,0) NOT NULL,
  description VARCHAR(255),
  visible BOOLEAN NOT NULL,
  sold_out BOOLEAN NOT NULL,
  sort_order INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 메뉴 옵션 그룹
CREATE TABLE menu_option_groups (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  menu_id BIGINT NOT NULL,
  name VARCHAR(30) NOT NULL,
  sort_order INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 메뉴 옵션 값
CREATE TABLE menu_option_values (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  menu_option_groups_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  additional_price DECIMAL(10,0) NOT NULL,
  sold_out BOOLEAN NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 가게 카테고리 ex) 한식, 분식, 중식, 치킨 ...
CREATE TABLE categories (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  store_category VARCHAR(10) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
