ALTER TABLE menu_image
MODIFY COLUMN storage_key VARCHAR(512) NOT NULL,
MODIFY COLUMN original_name VARCHAR(255) NULL,
MODIFY COLUMN saved_name    VARCHAR(128) NOT NULL,
MODIFY COLUMN content_type  VARCHAR(64)  NOT NULL;

ALTER TABLE store_image
MODIFY COLUMN storage_key VARCHAR(512) NOT NULL,
MODIFY COLUMN original_name VARCHAR(255) NULL,
MODIFY COLUMN saved_name    VARCHAR(128) NOT NULL,
MODIFY COLUMN content_type  VARCHAR(64)  NOT NULL;
