CREATE TABLE payment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  price DECIMAL(10,0) NOT NULL,
  merchant_uid VARCHAR(100) NOT NULL,
  imp_uid VARCHAR(100) NULL,
  status VARCHAR(30) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
 );

CREATE TABLE outbox_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id BINARY(16) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  aggregate_id BIGINT NULL,
  aggregate_type VARCHAR(30) NULL,
  status VARCHAR(20) NOT NULL,
  partition_key VARCHAR(128) NOT NULL,
  payload TEXT NOT NULL,
  occurred_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  processed_at DATETIME(6) NULL
);
