CREATE TABLE delivery (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  rider_id BIGINT NULL,
  status VARCHAR(20),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE rider (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name BIGINT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  homeDongCode VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  withdrawn_at DATETIME DEFAULT NULL
);

CREATE TABLE outbox_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id BINARY(16) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  aggregate_id BIGINT NULL,
  aggregate_type VARCHAR(30) NULL,
  status VARCHAR(20) NOT NULL,
  partition_key VARCHAR(128) NOT NULL,
  payload TEXT NOT NULL,
  occurred_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  processed_at DATETIME(6) NULL
);

CREATE TABLE inbox_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(36) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
 );
