CREATE TABLE admin_dong (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  admin_code VARCHAR(10) NOT NULL UNIQUE,
  name       VARCHAR(50) NOT NULL,
  polygon       MULTIPOLYGON SRID 4326 NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE legal_dong (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  legal_code VARCHAR(10) NOT NULL UNIQUE,
  name       VARCHAR(50) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE dong_mapping (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  legal_dong_id BIGINT NOT NULL,
  admin_dong_id BIGINT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
