rootProject.name = 'bappul'

include 'shared'
include 'shared:common-exception'
include 'shared:common-web'
include 'shared:common-security'
include 'shared:common-image'
include 'shared:common-logging'
include 'shared:message-relay'
include 'service'
include 'service:gateway'
include 'service:service-discovery'
include 'service:user'
include 'service:catalog'
include 'service:cart'
include 'service:promotion'
include 'service:order'
include 'service:payment'
include 'service:delivery'
include 'service:location'
