### 로그인
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "securePass123"
}

> {%
  client.global.set("token", "Bearer " + response.body.accessToken);
%}

### 가게 검색
GET http://localhost:8000/api/v1/stores/search
Content-Type: application/json

### 특정 가게 메뉴 목록 조회
GET http://localhost:8000/api/v1/stores/1

### 가게 등록
POST http://localhost:8000/api/v1/admin/stores
Authorization: {{token}}
Content-Type: application/json

{
  "categoryId" : 3,
  "ownerId" : 2,
  "name": "분식집",
  "phoneNumber" : "01012345678",
  "address" : "분식시 분식동 분식리",
  "introduction" :  "분식집입니다.",
  "minOrderPrice" : 10000,
  "deliveryFee" : 4000,
  "openStatus" : false
}
