-- 주소
CREATE TABLE address (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  alias VARCHAR(20),
  zipcode VARCHAR(10) NOT NULL,
  road_address VARCHAR(255) NOT NULL,
  detail_address VARCHAR(255),
  is_default BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL
);
